// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5ouTkNPMy62KolaJenJeohOPPfJzFEO4',
    appId: '1:683792329871:web:6d3b1cc42a0d7151b794fa',
    messagingSenderId: '683792329871',
    projectId: 'fir-anailytics',
    authDomain: 'fir-anailytics.firebaseapp.com',
    storageBucket: 'fir-anailytics.appspot.com',
    measurementId: 'G-DDSQWT431G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcktBfeOijjQiztfWEpHP33SvZbwTCI2M',
    appId: '1:683792329871:android:9171f8613a09f424b794fa',
    messagingSenderId: '683792329871',
    projectId: 'fir-anailytics',
    storageBucket: 'fir-anailytics.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3De763NThLZu6fF8BDp4b4CxD-nz9Z7M',
    appId: '1:683792329871:ios:da826c1025c7867eb794fa',
    messagingSenderId: '683792329871',
    projectId: 'fir-anailytics',
    storageBucket: 'fir-anailytics.appspot.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3De763NThLZu6fF8BDp4b4CxD-nz9Z7M',
    appId: '1:683792329871:ios:ae8107f54875f2d1b794fa',
    messagingSenderId: '683792329871',
    projectId: 'fir-anailytics',
    storageBucket: 'fir-anailytics.appspot.com',
    iosBundleId: 'com.example.ecommerce.RunnerTests',
  );
}
